// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWJDhnohSpOAx4UlMkNp1fwjdArnyFSXc',
    appId: '1:379312428600:web:a8fa93f0701d56fca2f8cd',
    messagingSenderId: '379312428600',
    projectId: 'project-yp-55c23',
    authDomain: 'project-yp-55c23.firebaseapp.com',
    storageBucket: 'project-yp-55c23.firebasestorage.app',
    measurementId: 'G-XFDLLC710H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD68YP8O-4R1EHl6sOYr69kPYX-Ec5wqvo',
    appId: '1:379312428600:android:96dc5d30a71d20efa2f8cd',
    messagingSenderId: '379312428600',
    projectId: 'project-yp-55c23',
    storageBucket: 'project-yp-55c23.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUPPWxft1xHD_bRGJHAm926GdRqwyCza8',
    appId: '1:379312428600:ios:4f52b3d51fe1139aa2f8cd',
    messagingSenderId: '379312428600',
    projectId: 'project-yp-55c23',
    storageBucket: 'project-yp-55c23.firebasestorage.app',
    androidClientId: '379312428600-cmje2o4h083qjo466i10vik2g2v800bu.apps.googleusercontent.com',
    iosClientId: '379312428600-l99pckdf5hmmudfontjel3b9big2e0gc.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectyp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUPPWxft1xHD_bRGJHAm926GdRqwyCza8',
    appId: '1:379312428600:ios:4f52b3d51fe1139aa2f8cd',
    messagingSenderId: '379312428600',
    projectId: 'project-yp-55c23',
    storageBucket: 'project-yp-55c23.firebasestorage.app',
    androidClientId: '379312428600-cmje2o4h083qjo466i10vik2g2v800bu.apps.googleusercontent.com',
    iosClientId: '379312428600-l99pckdf5hmmudfontjel3b9big2e0gc.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectyp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWJDhnohSpOAx4UlMkNp1fwjdArnyFSXc',
    appId: '1:379312428600:web:54cac0628916ec04a2f8cd',
    messagingSenderId: '379312428600',
    projectId: 'project-yp-55c23',
    authDomain: 'project-yp-55c23.firebaseapp.com',
    storageBucket: 'project-yp-55c23.firebasestorage.app',
    measurementId: 'G-BMR04D3P2E',
  );
}
